openapi: '3.0.3'
info:
  title: MassBank Minio API
  version: "0.1"
servers:
  - url: https://localhost:8081/
components:
  schemas:
    Connection:
      type: object
      properties:
        minio:
          type: object
          properties:
            endpoint:
              type: string
              nullable: false
            username:
              type: string
            password:
              type: string
            useSsl:
              type: boolean
        target:
          type: object
          properties:
            url:
              type: string
            username:
              type: string
            password:
              type: string
            authmethod:
              type: string
        filter:
          type: object
          properties:
            bucket:
              type: string
            prefix:
              type: string
            suffix:
              type: string
        validate:
          type: string
          default: "massbankv2"
paths:
  /config/addConnection:
    post:
      operationId: addConnection
      responses:
        '200':
          description: OK
        '409':
           description: Could not insert dataset
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Connection'
  /config/connections:
    get:
      operationId: getConnections
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Connection'
        '404':
            description: Not Found
        '500':
            description: Internal error
    delete:
      operationId: deleteAllConnections
      responses:
        '200':
          description: OK
        '400':
          description: error




