services:
  mb-minio-service:
    build:
      context: ../src/
      dockerfile: Dockerfile-debug
    ports:
      - 40000:40000
    cap_add:
      - SYS_PTRACE
    security_opt:
      - "apparmor=unconfined"
    volumes:
      - ./log:/var/log
  minio:
    image: minio/minio
    restart: always
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin