FROM golang:1.18 AS build-debug
WORKDIR /go/src
COPY . .
VOLUME /var/log

ENV CGO_ENABLED=0
RUN go get -d -v ./...

RUN go build -a -gcflags="all=-N -l" -installsuffix cgo -o openapi .

RUN go install github.com/go-delve/delve/cmd/dlv@latest

FROM scratch AS runtime
VOLUME /tmp
COPY --from=build-debug /go/src/openapi ./
COPY --from=build-debug /go/bin/dlv /
EXPOSE 8080/tcp 40000

CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/src"]

