/*
 * MassBank Minio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"encoding/json"
	"github.com/uly55e5/mbServices/src/redisstore"
)

// DefaultApiService is a service that implements the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// AddConnection -
func (s *DefaultApiService) AddConnection(ctx context.Context, connection Connection) (ImplResponse, error) {
	j, err := json.Marshal(connection)
	if err != nil {
		return Response(409, nil), nil
	}
	js := string(j)
	err = redisstore.StoreConnection(js)
	if err == nil {
		return Response(200, nil), nil
	}
	return Response(409, nil), nil
}
