/*
 * MassBank Minio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ConnectionTarget struct {
	Url string `json:"url,omitempty"`

	Username string `json:"username,omitempty"`

	Password string `json:"password,omitempty"`

	Authmethod string `json:"authmethod,omitempty"`
}

// AssertConnectionTargetRequired checks if the required fields are not zero-ed
func AssertConnectionTargetRequired(obj ConnectionTarget) error {
	return nil
}

// AssertRecurseConnectionTargetRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ConnectionTarget (e.g. [][]ConnectionTarget), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseConnectionTargetRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aConnectionTarget, ok := obj.(ConnectionTarget)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertConnectionTargetRequired(aConnectionTarget)
	})
}
