/*
 * MassBank Minio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Connection struct {
	Minio ConnectionMinio `json:"minio,omitempty"`

	Target ConnectionTarget `json:"target,omitempty"`

	Filter ConnectionFilter `json:"filter,omitempty"`

	Validate string `json:"validate,omitempty"`
}

// AssertConnectionRequired checks if the required fields are not zero-ed
func AssertConnectionRequired(obj Connection) error {
	if err := AssertConnectionMinioRequired(obj.Minio); err != nil {
		return err
	}
	if err := AssertConnectionTargetRequired(obj.Target); err != nil {
		return err
	}
	if err := AssertConnectionFilterRequired(obj.Filter); err != nil {
		return err
	}
	return nil
}

// AssertRecurseConnectionRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Connection (e.g. [][]Connection), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseConnectionRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aConnection, ok := obj.(Connection)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertConnectionRequired(aConnection)
	})
}
