/*
 * MassBank Minio API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ConnectionFilter struct {
	Bucket string `json:"bucket,omitempty"`

	Prefix string `json:"prefix,omitempty"`

	Suffix string `json:"suffix,omitempty"`
}

// AssertConnectionFilterRequired checks if the required fields are not zero-ed
func AssertConnectionFilterRequired(obj ConnectionFilter) error {
	return nil
}

// AssertRecurseConnectionFilterRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ConnectionFilter (e.g. [][]ConnectionFilter), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseConnectionFilterRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aConnectionFilter, ok := obj.(ConnectionFilter)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertConnectionFilterRequired(aConnectionFilter)
	})
}
